### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by tothattila87** [DanielPalatinszky/Journaley#1]
Nincs travis a project-ben.

**Comment by tothattila87** [comment]
Én neki esek kell még egy fő. Valaki?

**Comment by Wastack** [comment]
Én nagyon szeretnék nekiesni (pro tipp: nekiesni egybe van)

**Comment by tothattila87** [comment]
Commit link:
[https://github.com/NewBoy22/Journaley/commit/4b9d9253dcb39c84578411c477f89d847aac0d5b](https://github.com/NewBoy22/Journaley/commit/4b9d9253dcb39c84578411c477f89d847aac0d5b)

véletlenül felment .vs mappa is , hozzáadva gitignorehoz

**Comment by tothattila87** [comment]
nem megy mert folyton mono-val akar buildelni...
