### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by tothattila87** [DanielPalatinszky/Journaley#3]
mivel a travis nem ment , ezt próbáljuk Tomival!!!

**Comment by Wastack** [comment]
Yeah, let's rock... it's my pleasure to contribute to this issue.

**Comment by tothattila87** [comment]
A commit:[https://github.com/NewBoy22/Journaley/commit/53f7c9dde13e50acb4270d07ed9cb4bf790c0cd8](https://github.com/NewBoy22/Journaley/commit/53f7c9dde13e50acb4270d07ed9cb4bf790c0cd8)

appveyor.yml hozzáadása

**Comment by tothattila87** [comment]
jó az appveyor lefutott !!! 

22 tesztből 8 ment át és 14 hasalt el.

**Comment by DanielPalatinszky** [comment]
Ellenőrizve, működik minden és az AppVeyor Team is jó.

**Comment by micskeiz** [comment]
OK
