### ISSUE TITLE
ReSharper és SonarLint

### ISSUE THREAD

**Issue by DanielPalatinszky** [DanielPalatinszky/Journaley#4]
Statikus kód analízis kéne és a hibák javítása!

**Comment by DanielPalatinszky** [comment]
[Obsolete Font call fix](https://github.com/NewBoy22/Journaley/commit/0a991ec582285ff241fcc5ff6301ec659c92c9b0)

**Comment by Wastack** [comment]
Replaced all the tabs with 4 spaces.
see: https://github.com/NewBoy22/Journaley/commit/e10157c9fa13630c06468105434d767735afeadd

**Comment by Wastack** [comment]
Remove all the trailing whitespaces in charp files (*.cs).
see: https://github.com/NewBoy22/Journaley/commit/55cd92eee7d33f981da66eb761eae9f44d94ea16

**Comment by Wastack** [comment]
Remove css redundancies.
see: https://github.com/NewBoy22/Journaley/commit/711098878f1addaddb4c77fbce7e11fd44ee7164

**Comment by Wastack** [comment]
fix MD5 hash and
use right order of modifiers for Image property.
see: https://github.com/NewBoy22/Journaley/commit/573e0fd9ef02b70b38daa3c605a361bbbb125578

**Comment by Wastack** [comment]
Remove unnecessary Where from query. Use parameter of Count instead.
see: https://github.com/NewBoy22/Journaley/commit/340b81a8d5532a2f5c6b39d87efc7f655a8b7e8d

**Comment by Wastack** [comment]
Use auto-property instead of explicit private set.
see: https://github.com/NewBoy22/Journaley/commit/0184eccc9762db32de3982bce41446eebdfbe745

**Comment by Wastack** [comment]
Further using of auto-property instead of explicit private set.
see: https://github.com/NewBoy22/Journaley/commit/e8e642ee02a22d740bd3700e7b7c4bb53095816b

**Comment by DanielPalatinszky** [comment]
[Removed unused usings](https://github.com/NewBoy22/Journaley/commit/e1a2ae7f9bc4a67713f572903a01c7787d53a1c0)

**Comment by Wastack** [comment]
I like your commit NewBoy22. Really awesome. Thank you.

**Comment by DanielPalatinszky** [comment]
Thank you, you are sooooooooo kind

**Comment by Wastack** [comment]
Check out Attila's new commit. Great guy. Awesome work.
Join assignment with declarations.
see: https://github.com/NewBoy22/Journaley/commit/4745102ead9bb33a836f7be0971321ad31c8fb11

**Comment by Wastack** [comment]
Wow. Check out this new stuff. Such clean code. Love it..
Make auto-properties get-only.
see: https://github.com/NewBoy22/Journaley/commit/27f8befe37c2d883cad11db1268fcec32751db54

**Comment by DanielPalatinszky** [comment]
[Using Count instead of Count()](https://github.com/NewBoy22/Journaley/commit/90af597d442fa2717ca8244417f0ed389371f7c2)

**Comment by Wastack** [comment]
516cfa1 ("changed some prop to readonly", 2017-04-12)

**Comment by Wastack** [comment]
52540c6 ("changed 2 prop to private", 2017-04-12)

**Comment by Wastack** [comment]
9a14f20 ("deleted empry statement", 2017-04-12)

**Comment by Wastack** [comment]
4ac00dd ("Using expression bodies", 2017-04-12)

**Comment by Wastack** [comment]
3c688f3 ("moved variables into inner scope where it used", 2017-04-12)

**Comment by Wastack** [comment]
27386e7 ("specify string comparsion mode", 2017-04-12)

**Comment by Wastack** [comment]
529031d ("added some null checks where it needed", 2017-04-12)

**Comment by Wastack** [comment]
97502cc ("changed the namescape to the correct file name", 2017-04-12)

**Comment by Wastack** [comment]
5c31b0f ("used collection initzializer where i could", 2017-04-12)

**Comment by Wastack** [comment]
76b04bb ("used string interpolation expression where i could", 2017-04-12)

**Comment by Wastack** [comment]
fd56a27 ("used object initializer where i could", 2017-04-12)

**Comment by Wastack** [comment]
9f66169 ("used nameof instead of strings..", 2017-04-12)

**Comment by Wastack** [comment]
158dc91 ("changed 326 != to null propagation....by hand.........", 2017-04-12)
9ab0cf1 ("used ?? expression where i could", 2017-04-12)
2830e6b ("converted for-loops to foreach", 2017-04-12)
e9f0ffa ("invoke as extension method", 2017-04-12)
4a081f5 ("merged seq checks and cond expressions", 2017-04-12)
3718552 ("convert to ?: expression", 2017-04-12)
81a0185 ("joined declaration and assignement", 2017-04-12)
fabacd3 ("merged 2 methods with optional param", 2017-04-12)

**Comment by Wastack** [comment]
Nice statistics: 82143 lines added, 42281 removed for this issue so far.

**Comment by tothattila87** [comment]
toltam "pár" commitot huehuehue

**Comment by Wastack** [comment]
5a9998d ("replace tabs with 4 spaces", 2017-04-12)
fe0517c ("joined null checks with the assignments", 2017-04-12)
03fca2e ("removed the redundant base constructor call", 2017-04-12)
65bcab1 ("removed not used local variables", 2017-04-12)
f75e8ca ("removed redundant default values", 2017-04-12)
f09e2da ("removed int from enum as its by default int...", 2017-04-12)
aec9a1b ("removed redundant method overrides and empty constructors", 2017-04-12)
586c000 ("removed not used method", 2017-04-12)
f6b7019 ("remplace tabs with spaces", 2017-04-12)

**Comment by tothattila87** [comment]
remplace GG EASY

**Comment by tothattila87** [comment]
nah volt egy kis gond az appveyorral . a ?? operátort nem ismeri ezért vissza kellett vonni 2 commit-ot. Megoldódott. BTW végig értünk a warning-okon hurray!!! 
Már csak a teszteket kell kijavítani és sinen vagyunk !

**Comment by Wastack** [comment]
39ccd091643810d6b75d1a7a1e4f7dc359486a95 remove trailing whitespaces
38867936b24e9c4686664208dc7f31e94c5a8d06 replace tabs with 4 spaces
31111d6a520b50b88548012a0dd9258f4312d984 CultureInfo and path fixes -> every test passes
39bc8e704855a25ba4daf54c976424c3fe4b0364 Fixed decimal parse by using invariant culture
f592dea9cc166d16df796820837d0c9c19b84d1d Using ExecutingAssembly instead of EntryAssembly (same value but testable)
e36ec8604a5e342c6461c8f1b33f73126f89c7ea dayEnabled changed to inner scope variable
1751ecc70a741e2dafe3c55dae2e93fd1877bab6 removed always true expressions
a4e9a3b1cac92fcc7adfd9a2320a32c45c42d5dd changed to operator "is"
df5194712c394d4e538fa61c292fe05ee7b870a3 Float comparison fixed #2
aef1c0e27d5805c99316e7bbdd59f35beda03b3b Float comparison fixed
dd6f7d7bad1b0ea20ec5e2dd985510752bd9f493 revert "joined null checks with the assignments"
c2c9ed470f8a79ad06876b68790e69b4446e5089 Revert "changed reference comparisons to value comparisons"
038f23e3a3c0543a5d4b88cdb903e25781ae9c6f changed reference comparisons to value comparisons
f4008c7ea890bb23aebe94662886ecc90c5689c8 changed 2 classes to sealed - virtual member called in constructor...

**Comment by Wastack** [comment]
Good job guys.

**Comment by micskeiz** [comment]
OK, you have done lots of fixing.
