### ISSUE TITLE
Fixing tests

### ISSUE THREAD

**Issue by DanielPalatinszky** [DanielPalatinszky/Journaley#5]
14 out of 22 tests not working properly

**Comment by DanielPalatinszky** [comment]
[Bad assembly call fix](https://github.com/NewBoy22/Journaley/commit/f592dea9cc166d16df796820837d0c9c19b84d1d)

**Comment by DanielPalatinszky** [comment]
[Decimal parse fix](https://github.com/NewBoy22/Journaley/commit/39bc8e704855a25ba4daf54c976424c3fe4b0364)

**Comment by DanielPalatinszky** [comment]
[Culture info fixes](https://github.com/NewBoy22/Journaley/commit/31111d6a520b50b88548012a0dd9258f4312d984)

**Comment by DanielPalatinszky** [comment]
All tests are working properly

**Comment by tothattila87** [comment]
well fckin done ! checked those , everything workin now !! appveyor seems happy too

**Comment by micskeiz** [comment]
OK, but try to use more professional comments.
